### ISSUE TITLE
[FR] Define default colors in plugin settings

### ISSUE THREAD

**Issue by TomDeSmet** [alecritson/craft-spectrum-fieldtype#4]
It would be nice if we could define a default color list in the plugin settings instead of only in the field settings. This color list could be the default for all spectrum fields and would be overwritten by the field settings.

The reason for this is that I have multiple spectrum fields in a single entry type. So I cannot re-use a single spectrum field. Hence, I need to copy paste every color manually from field to field.

**Comment by alecritson** [comment]
Hey @TomDeSmet 

I've created a new branch with version [`0.9.2`](https://github.com/alecritson/craft-spectrum-fieldtype/tree/add-default-palette) which now covers adding a default palette so you don't have to keep copy pasting bits.

Once you have updated from that branch you just define your default palette in the plugin settings and then on the input field you just need to check `Use default palette?` which will then merge them in to your custom palette.

Let me know how this works for you 👍

**Comment by TomDeSmet** [comment]
That's just perfect!
And probably the fastest reply/update ever :) Great job!

**Comment by alecritson** [comment]
Not a problem :)
